export const dom = {
scCidInput:             document.getElementById('sc-cid-input'),
htmlInput:              document.getElementById('html-input'),
htmlInputWrapper:       document.getElementById('html-input-wrapper'),
dropOverlay:            document.getElementById('drop-overlay'),
htmlInputLabel:         document.getElementById('html-input-label'),
resultsPanel:           document.getElementById('results-panel'),
refactorButton:         document.getElementById('refactor-button'),
sandboxFrame:           document.getElementById('sandbox-frame'),
auditSpinner:           document.getElementById('audit-spinner'),
refactorModal:          new bootstrap.Modal(document.getElementById('refactorModal')),
refactoredCodeTextarea: document.getElementById('refactored-code'),
copyCodeButton:         document.getElementById('copy-code-button'),
diffPanel:              document.getElementById('diff-panel'),
uploadButton:           document.getElementById('upload-button'),
fileInput:              document.getElementById('upload-file-input'),
uploadError:            document.getElementById('upload-error'),
modeFullRadio:          document.getElementById('html-mode-full'),
modeBodyRadio:          document.getElementById('html-mode-body'),
previewToggleBtn:       document.getElementById('preview-toggle-btn'),
previewPane:            document.getElementById('preview-pane'),
themeToggleBtn:         document.getElementById('theme-toggle-btn'),
disabledBannerHost:     document.getElementById('disabled-banner-host'),
settingsBtn:            document.getElementById('settings-btn'),
settingsOffcanvas:      new bootstrap.Offcanvas(document.getElementById('settingsOffcanvas')),
settingsForm:           document.getElementById('settings-form'),
settingsResetBtn:       document.getElementById('settings-reset-btn'),
};
